const GET_PLACES = 'GET_PLACES'
const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
const GET_PLACES_FAIL = 'GET_PLACES_FAIL';

const GET_SINGLE_PLACE = 'GET_SINGLE_PLACE'
const GET_SINGLE_PLACE_SUCCESS = 'GET_SINGLE_PLACE_SUCCESS'
const GET_SINGLE_PLACE_FAIL = 'GET_SINGLE_PLACE_FAIL'

const GET_MARKERS = 'GET_MARKERS';
const GET_MARKERS_SUCCESS = 'GET_MARKERS_SUCCESS';
const GET_MARKERS_FAIL = 'GET_MARKERS_FAIL';

const UPDATE_PLACE_TYPE = 'UPDATE_PLACE_TYPE'

const CLEAR_SINGLEPLACE = 'CLEAR_SINGLEPLACE'

const SEND_PLACES = 'SEND_PLACES'
const SET_NOTIFICATION = 'SET_NOTIFICATION'

const GET_PLACETYPE_OPTIONS = 'GET_PLACETYPE_OPTIONS'

const USER_LOADED = 'USER_LOADED'
const USER_LOADING = 'USER_LOADING'
const AUTH_ERROR = 'AUTH_ERROR'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILED = 'LOGIN_FAILED'
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
const REGISTER_FAIL = 'REGISTER_FAIL'
const GET_ERRORS = 'GET_ERRORS'
const CLEAR_ERRORS = 'CLEAR_ERRORS'

const UPDATE_COORDINATES = 'UPDATE_COORDINATES'

export default {
  GET_PLACES,
  GET_PLACES_SUCCESS,
  GET_PLACES_FAIL,
  GET_SINGLE_PLACE,
  GET_SINGLE_PLACE_SUCCESS,
  GET_SINGLE_PLACE_FAIL,
  GET_MARKERS,
  GET_MARKERS_SUCCESS,
  GET_MARKERS_FAIL,
  UPDATE_PLACE_TYPE,
  CLEAR_SINGLEPLACE,
  SEND_PLACES,
  SET_NOTIFICATION,
  GET_PLACETYPE_OPTIONS,
  USER_LOADED,
  USER_LOADING,
  LOGOUT_SUCCESS,
  LOGIN_FAILED,
  AUTH_ERROR,
  LOGIN_SUCCESS,
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  UPDATE_COORDINATES,
  GET_ERRORS,
  CLEAR_ERRORS
}
