export const GET_PLACES = 'GET_PLACES'
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
export const GET_PLACES_FAIL = 'GET_PLACES_FAIL';

export const GET_SINGLE_PLACE = 'GET_SINGLE_PLACE'
export const GET_SINGLE_PLACE_SUCCESS = 'GET_SINGLE_PLACE_SUCCESS'
export const GET_SINGLE_PLACE_FAIL = 'GET_SINGLE_PLACE_FAIL'

export const GET_MARKERS = 'GET_MARKERS';
export const GET_MARKERS_SUCCESS = 'GET_MARKERS_SUCCESS';
export const GET_MARKERS_FAIL = 'GET_MARKERS_FAIL';

export const UPDATE_PLACE_TYPE = 'UPDATE_PLACE_TYPE'

export const CLEAR_SINGLEPLACE = 'CLEAR_SINGLEPLACE'

export const SEND_PLACES = 'SEND_PLACES'
export const SET_NOTIFICATION = 'SET_NOTIFICATION'

export const GET_PLACETYPE_OPTIONS = 'GET_PLACETYPE_OPTIONS'

export const USER_LOADED = 'USER_LOADED'
export const USER_LOADING = 'USER_LOADING'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
