export const GET_PLACES = 'GET_PLACES'
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS'
export const GET_PLACES_FAIL = 'GET_PLACES_FAIL'

export const GET_SINGLE_PLACE = 'GET_SINGLE_PLACE'
export const GET_SINGLE_PLACE_SUCCESS = 'GET_SINGLE_PLACE_SUCCESS'
export const GET_SINGLE_PLACE_FAIL = 'GET_SINGLE_PLACE_FAIL'

export const SEND_PLACES = 'SEND_PLACES'
export const SEND_PLACES_SUCCESS = 'SEND_PLACES_SUCCESS'
export const SEND_PLACES_FAIL = 'SEND_PLACES_FAIL'

export const SET_NOTIFICATION = 'SET_NOTIFICATION'

export const GET_PLACETYPE_OPTIONS = 'GET_PLACETYPE_OPTIONS'
export const GET_PLACETYPE_OPTIONS_SUCCESS = 'GET_PLACETYPE_OPTIONS_SUCCESS'
export const GET_PLACETYPE_OPTIONS_FAIL = 'GET_PLACETYPE_OPTIONS_FAIL'

export const USER_LOADED = 'USER_LOADED'
export const USER_LOADING = 'USER_LOADING'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
